Add missing bazel_binaries attr in README
Otherwise the bazel_integration_test target will fail to build with a
message like so:

```
ERROR: Skipping '@build_bazel_bazel_7_6_1': No repository visible as '@build_bazel_bazel_7_6_1' from main repository
```